<div class="container-fluid container-fullw padding-bottom-10">
<div class="row">

    <div class="col-sm-6">
        <div class="alert alert-block alert-success fade in">
            <h4 class="alert-heading margin-bottom-10 text-bold"><i class="fa fa-info-circle"></i> KENEYA</h4>
            <p class="margin-bottom-10">
                Votre opération a été bien prise en compte
            </p>
        </div>
    </div>

</div>
</div>
<script type="text/JavaScript">
    setTimeout(function () {
    window.location.href = "<?php echo $this->baseUrl().$this->URL[1];?>";
    }, 5000);
</script>

