

<h2 class="az-content-title tx-24 mg-b-5">
    <div dropdown="">
        <span class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-cog"></i> RECHERCHE
        </span>
    </div>
</h2>

<p class="mg-b-20 mg-lg-b-25">Résultats de recherche avec le critère [ <b><?php echo $this->search;?></b> ]</p>

<div class="row row-sm">

    <div class="col-lg-8">
        <div class="card card-table-two">

            <div class="table-responsive">
            <table id="dataTable" class="display responsive nowrap">
            <thead>
              <tr>
                <th class="wd-25p">Nom & Prénoms</th>
                <th class="wd-5p">Sexe</th>
                <th class="wd-10p">Référence</th>
                <th class="wd-15p">Niveau & Classe</th>
                <th class="wd-15p">Père</th>
                <th class="wd-15p">Mère</th>
                <th class="wd-10p">Photo</th>
                <th class="wd-5p">Actions</th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($this->eleves as $u) :
              if(file_exists("tmp/".$u['tmp']) && !empty($u['tmp']))$IMG=$this->baseUrl()."/tmp/".$u['tmp'];
              else $IMG = $this->baseUrl()."/private/assets/images/media-user.png";
              ?>
              <tr class="tx-white <?php echo ($u['type']==1)?'bg-primary':'bg-success'; ?>">
                <td class="tx-bold <?php echo ($u['sexe']=='H')?'tx-dark':'tx-danger'; ?>"><?php echo $u['nom'].' '.$u['prenom']; ?></td>
                <td class="<?php echo ($u['sexe']=='H')?'bg-dark':'bg-danger'; ?>"><?php echo $u['sexe']; ?></td>
                <td><?php echo $u['reference']; ?></td>
                <td class=""><?php echo $u['niveau']." / ".$u['classe']." / ";?><?php echo ($u['type']==1)?'NON AFFECTE':'AFFECTE'; ?></td>
                <td><?php echo $u['pere']; ?></td>
                <td><?php echo $u['mere']; ?></td>
                <td><img src="<?php echo $IMG;?>" alt="" class="img-rounded" width="30px" height="30px"></td>
                <td>
                <div dropdown="">
                        <span class="btn btn-dark dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            <i class="fa fa-cog"></i> Actions <span class="caret"></span>
                        </span>
                        <div class="dropdown-menu">
                            <a href="<?php echo $this->baseUrl();?>/principal/eleve/detail/id/<?php echo $u['id_ecole'];?>/c/<?php echo $u['id_ecole_classe'];?>/e/<?php echo $u['id_eleve']; ?>" class="dropdown-item">Dossier élève</a>
                        </div><!-- dropdown-menu -->
                    </div>
                </td>
              </tr>
              <?php endforeach; ?>
            </tbody>
          </table>      
            </div><!-- table-responsive -->
        </div><!-- card-dashboard-five -->
    </div>


    


    
    



</div>

<script src="<?php echo $this->baseUrl(); ?>/private/azia/lib/jquery/jquery.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/private/azia/lib/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/private/azia/lib/datatables.net-dt/js/dataTables.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/private/azia/lib/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/private/azia/lib/datatables.net-responsive-dt/js/responsive.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/private/azia/lib/select2/js/select2.min.js"></script>

<script>
$(document).ready(function(){
    'use strict';

    $('#dataTable').DataTable({
            responsive: true,
            language: {
            searchPlaceholder: 'Rechercher un élève...',
            sSearch: '',
            lengthMenu: '_MENU_ /page',
        }
    });


    // Select2
    $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });

});
</script>




