<link href="<?php echo $this->baseUrl(); ?>/private/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
<link href="<?php echo $this->baseUrl(); ?>/private/azia/lib/select2/css/select2.min.css" rel="stylesheet">

<div class="breadLine">
    <div class="breadCrumbsLeft">
        <ul>
            <li><a href="<?php echo $this->baseUrl(); ?>/principal/dashboard"><i class="ti-home"></i> Dashboard</a></li>
            <li class="current"><a href="#">Envoi SMS destinataire unique</a></li>
        </ul>
    </div>
</div>

<h2 class="az-content-title tx-24 mg-b-5">ENVOI SMS UNIQUE</h2>
<p class="mg-b-20 mg-lg-b-25"><a href="<?php echo $this->baseUrl(); ?>/principal/sandbox/rapid-sms-multiple">Cliquez ici pour envoyer un SMS à plusieurs destinaires</a></p>



<div class="row row-sm">

    <div class="col-lg-4 mg-b-20">

        <form method="post">
        <div class="card card-table-two">
            <div class="az-content-label mg-b-5">DESTINATAIRE UNIQUE</div>
            <p class="mg-b-20">Envoyez un message à un destinataire unique</p>
                
            <div class="row row-sm">

                <div class="form-group col-12"><?php echo $this->message;?></div>
                <div class="form-group col-12">
                    <label class="control-label">N°Téléphone <span class="symbol required"></span></label>
                    <input type="text" class="form-control" name="telephone" placeholder="N°Téléphone" required>
                </div>
                <div class="form-group col-12">
                    <label class="control-label">Message <span class="symbol required"></span></label>
                    <textarea class="form-control" name="sms" placeholder="Message" required></textarea>
                </div>
                <div class="form-group col-12">
                    <input type="submit" class="btn btn-squared btn-primary form-control" value="Envoyer">
                </div>

            </div><!-- row -->
        </div><!-- card-dashboard-five -->
        <form>

    </div>


    

    

</div>



<script src="<?php echo $this->baseUrl(); ?>/private/azia/lib/jquery/jquery.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/private/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<script>

$(function(){
        'use strict'

        $(document).ready(function(){

          $('.select2').select2({
            placeholder: 'Choisissez un élément'
          });

          $('.select2-no-search').select2({
            minimumResultsForSearch: Infinity,
            placeholder: 'Choisissez un élément'
          });
        });

});

    var DatePicker = function () {
        "use strict";


        var datePickerHandler = function () {
            $('.datepicker').datepicker({
                autoclose: true,
                format: "yyyy-m-d",
                todayHighlight: true
            });

        };

        return {
            //main function to initiate template pages
            init: function () {
                datePickerHandler();
            }
        };
    }();

    jQuery(document).ready(function () {
        DatePicker.init();
    });
</script>
