
<div class="breadLine">
    <div class="breadCrumbsLeft">
        <ul>
            <li><a href="<?php echo $this->baseUrl(); ?>/"><i class="ti-home"></i> Home</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/site/dashboard">Dashboard</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/site/site-region/list/p/<?php echo $this->p; ?>/r/<?php echo $this->r; ?>"><?php echo $this->region['region']; ?></a></li>
            <li class="current"><a href="#"><?php echo $this->site['site']; ?></a></li>
        </ul>
    </div>
</div>

<div class="row row-sm">

    <div class="col-lg-4">
        
        <div class="row row-sm">

            <div class="col-lg-12">

                <div class="card bd-0">
                    <div class="card-header bg-gray-400 bd-b-0-f pd-b-0">
                    <nav class="nav nav-tabs">
                        <a class="nav-link active" data-toggle="tab" href="#tab1">FICHE TECHNIQUE</a>
                        <a class="nav-link" data-toggle="tab" href="#tab2">PHOTO</a>
                    </nav>
                    </div><!-- card-header -->
                    <div class="card-body bd bd-t-0 tab-content">
                        <div id="tab1" class="tab-pane active show">

                            <div class="card card-header tx-bold">
                                INFORMATIONS SITE TECHNIQUE
                            </div>
                            <div class="card card-table-two">   

                                <div class="row row-sm">
                                    <div class="form-group col-12">
                                        <label class="control-label">Référence du site</label>
                                        <input type="text" class="form-control tx-bold" value="<?php echo $this->site['reference']; ?>">
                                    </div> 
                                    <div class="form-group col-6">
                                        <label class="control-label">Libellé du site</label>
                                        <input type="text" class="form-control tx-bold" value="<?php echo $this->site['site']; ?>" >
                                    </div>  
                                    <div class="form-group col-6">
                                        <label class="control-label">Typologie du site</label>
                                        <input type="text" class="form-control tx-bold tx-danger" value="<?php echo $this->site['type_site']; ?>">
                                    </div>  
                                    <div class="form-group col-6">
                                        <label class="control-label">Ville / Commune</label>
                                        <input type="text" class="form-control" value="<?php echo $this->site['ville']." / ".$this->site['commune']; ?>">
                                    </div>
                                    <div class="form-group col-6">
                                        <label class="control-label">Quartier</label>
                                        <input type="text" class="form-control" value="<?php echo $this->site['quartier']; ?>">
                                    </div>
                                    <div class="form-group col-12">
                                        <label class="control-label">Responsable du site</label>
                                        <input type="text" class="form-control tx-bold tx-primary" value="<?php //echo $this->site['quartier']; ?>">
                                    </div>  
                                </div>

                            </div>

                        </div>
                        <div id="tab2" class="tab-pane">

                            <div class="row row-sm">
                                <div class="form-group col-8">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="customFile" name="fichier">
                                        <label class="custom-file-label" for="customFile">Ajouter des images du site</label>
                                    </div>
                                </div>
                                <div class="form-group col-4">
                                    <input type="submit" class="btn btn-squared btn-dark form-control" name="enregistrer-fichier" value="Enregistrer">
                                </div>
                            </div>
                            
                            <div class="card card-table-two">   
                                <div class="row row-sm">
                                      
                                </div>
                            </div>
                            
                        </div>

                    </div>
                </div>
                
            </div>

        </div>


    </div>


    <div class="col-lg-8">


        <div class="card bd-0">
            <div class="card-header bg-gray-400 bd-b-0-f pd-b-0">
                <nav class="nav nav-tabs">
                    <a class="nav-link active" data-toggle="tab" href="#tab0">DECLARER SALLE</a>
                    <?php foreach ($this->salles as $u) :?>
                    <a class="nav-link" data-toggle="tab" href="#tab<?php echo $u['reference']; ?>"><?php echo $u['salle']; ?></a>
                    <?php endforeach; ?>
                </nav>
            </div><!-- card-header -->
            <div class="card-body bd bd-t-0 tab-content">

                <div id="tab0" class="tab-pane active show">

                    <div class="row row-sm">
                        <div class="col-lg-4">
                            <div class="card card-header tx-bold">
                                SALLE TECHNIQUE
                            </div>
                            <div class="card card-table-two">  
                                <div class="row row-sm">
                                      <form id="formulaireSalle">

                                        <input type="hidden" name="site" class="id-site" value="<?php echo $this->site['id']; ?>">

                                    <div class="form-group col-12">
                                        <label class="control-label">Type de salle <span class="symbol required"></span></label>
                                        <select class="form-control select2-no-search type-salle" required name="type-salle">
                                            <option value="">(Type de salle)</option>
                                            <?php foreach ($this->types as $t) :?>
                                            <option value="<?php echo $t['id']; ?>"><?php echo $t['type_salle']; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                        <span class="erreur_type">  </span> 
                                    </div>
                                    <div class="form-group col-12">
                                        <label class="control-label">Référence de salle</label>
                                        <input type="text" name="reference-salle" class="form-control tx-bold reference-salle" value="SA<?php echo strtoupper(substr(md5(date("YHismd")),0,8)); ?>">
                                         <span class="erreur_reference">  </span> 
                                    </div> 

                                    <div class="form-group col-12">
                                        <label class="control-label">Libellé de salle</label>
                                        <input type="text" class="form-control salle" name="salle" value="Salle SA<?php echo strtoupper(substr(md5(date("YHismd")),0,8)); ?>">
                                        <span class="erreur_salle">  </span> 
                                    </div>

                                    <div class="form-group col-12">
                                        <input type="submit" class="btn btn-squared btn-dark form-control" value="Enregistrer">
                                    </div>
                                </form>
                                </div> 
                            </div>
                        </div>

                        <div class="col-lg-8">


                            <table id="dataTableS" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th class="wd-15p">Equipement</th>
                                        <th class="wd-5p">Quantité</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php $i=0;foreach ($this->elements as $e) :?>
                                    <input type="hidden" name="id-element-<?php echo $i; ?>" value="<?php echo $e['id']; ?>">
                                    <tr>
                                        <td class="tx-bold"><?php echo $e['element']; ?></td>
                                        <td><input type="text" name="quantite-element-<?php echo $i; ?>" class="form-control" value="0"></td>
                                    </tr>
                                    <?php $i++;endforeach; ?>
                                    <input type="hidden" name="total-element" value="<?php echo $i; ?>">
                                    </tbody>
                            </table> 
                        </div>

                    </div>

                </div>

                <?php foreach ($this->salles as $u) :?>
                <div id="tab<?php echo $u['reference']; ?>" class="tab-pane">

                    <div class="row row-sm">
                        <div class="col-lg-4">
                            <div class="card card-table-two">  
                                <div class="row row-sm">
                                    <div class="form-group col-12">
                                        <label class="control-label">Référence de salle</label>
                                        <input type="text" class="form-control tx-bold" value="<?php echo $u['reference']; ?>">
                                    </div>
                                    <div class="form-group col-12">
                                        <label class="control-label">Type de salle</label>
                                        <input type="text" class="form-control tx-bold" value="<?php echo $u['type_salle']; ?>">
                                    </div>
                                    <div class="form-group col-12">
                                        <label class="control-label">Libellé de salle</label>
                                        <input type="text" class="form-control tx-bold" value="<?php echo $u['salle']; ?>">
                                    </div>
                                </div> 
                            </div>
                        </div>

                        <div class="col-lg-8">

                            <div class="card bd-0">
                                <div class="card-header bg-gray-400 bd-b-0-f pd-b-0">
                                <nav class="nav nav-tabs">
                                    <a class="nav-link active" data-toggle="tab" href="#tabL<?php echo $u['reference']; ?>">ELEMENT</a>
                                    <a class="nav-link" data-toggle="tab" href="#tabN<?php echo $u['reference']; ?>">PHOTO</a>
                                </nav>
                                </div><!-- card-header -->
                                <div class="card-body bd bd-t-0 tab-content">
                                    <div id="tabL<?php echo $u['reference']; ?>" class="tab-pane active show">

                                        <table id="dataTable1" class="table table-bordered table-striped col-lg-12">
                                            <thead>
                                                <tr>
                                                    <th class="wd-15p">Element</th>
                                                    <th class="wd-5p">Quantité</th>
                                                    <th class="wd-5p">Actions</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php $i=0;foreach ($this->elements as $e) :?>
                                                <input type="hidden" name="id-element-<?php echo $i; ?>" value="<?php echo $e['id']; ?>">
                                                <tr>
                                                    <td class="tx-bold wd-15p">
                                                        <?php echo $e['element']; ?>
                                                    </td>
                                                    <td class="tx-bold wd-5p">
                                                        <span class="tx-bold">10</span>
                                                    </td>
                                                    <td class="tx-bold wd-5p">
                                                        <div dropdown="">
                                                            <span class="btn btn-dark dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                                <i class="fa fa-cog"></i> Actions <span class="caret"></span>
                                                            </span>
                                                            <div class="dropdown-menu">
                                                                <a href="#" class="dropdown-item">Modifier</a>
                                                                <a href="#" id="delete-<?php echo $u['id']; ?>" class="dropdown-item">Supprimer</a>
                                                            </div><!-- dropdown-menu -->
                                                        </div>
                                                    </td>
                                                </tr>
                                                <?php $i++;endforeach; ?>
                                                <input type="hidden" name="total-element" value="<?php echo $i; ?>">
                                            </tbody>
                                        </table>

                                    </div>
                                    <div id="tabN<?php echo $u['reference']; ?>" class="tab-pane">
                                        
                                        
                                        <form enctype="multipart/form-data" name="upload-form" id="file"  method="POST" action="<?php echo $this->baseUrl(); ?>/site/salles/upload">
                                            <div class="row row-sm">
                                            <input type="hidden" name="MAX_FILE_SIZE" value="100000" />
                                            <div class="form-group col-8">
                                                <div class="custom-fil">
                                                    <label class="custom-file-labe file" for="file">Ajouter des images de la salle</label>
                                                    <input type="file" class="custom-file-i" id="fichier" name="image"><br>
                                                    <input type="hidden" class="custom-file-i" value="<?php echo $u['id'];?>" id="fichier" name="idFile">
                                                    <span id="file_erreur"></span>
                                                </div>
                                            </div>
                                            <div class="form-group col-4">
                                                <input type="submit" class="btn btn-squared btn-dark form-control" name="enregistrer-fichier" value="Enregistrer">
                                            </div>
                                            </div>
                                        </form>
                                 
                                        
                                        
                                        <div class="card card-table-two">   
                                            <div class="row row-sm">
                                    <img src="<?php echo $this->baseUrl().'/public/images/'.$u["image"];?>" width="100"/>
                                            </div>
                                        </div>
                                        
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>

        
                <?php endforeach; ?>
            </div>
        </div>
        
        
    </div>


</div>


  


<script>
$(document).ready(function(){
  
  var form_data;
   var property
  var file_erreur="";
    $(document).on("change","#fichier", function(){
        property=document.getElementById("fichier").files[0];
       var image_name=property.name;
       var image_extension=image_name.split('.').pop().toLowerCase();
       //alert(image_extension); 

       //si on retourne -1, c'est que ce n'est pas une image
       if (jQuery.inArray(image_extension,['gif','png','jpg','jpeg'])==-1) {
        file_erreur="fichier non valide";
         $('#file_erreur').text(file_erreur);
         $('#file_erreur').css("color","red");
       } 

       var image_size= property.size;
       if (image_size>2000000) {
        file_erreur="Images de taille > 200 Ko n'est pas valide";
         $('#file_erreur').text(file_erreur);
         $('#file_erreur').css("color","red");
       } /*else{
          form_data=new FormData();
         file_erreur="";
         $('#file_erreur').text(file_erreur);
       }

    });
    
$('#file').on('submit', function (e) {
    e.preventDefault();

         if (file_erreur!="") {
          $('#file_erreur').text(file_erreur);
         $('#file_erreur').css("color","red");

         return false;
         }else{
             
              $.ajax({
                        type: 'POST',
                        data: {file:property},
                        url: "<?php echo $this->baseUrl(); ?>/site/salles/upload",
                        contenType:false,
                        cache:false,
                        processData:false,
                        beforeSend:function(){
                            $('#file_erreur').text("Chargement de l'image....");
                             $('#file_erreur').css("color","green");
                        },
                        success: function(data) {
                               alert(data);
                        }
                    });
         }*/
                   
    });  




 $('#formulaireSalle').on('submit', function (e) {
                    e.preventDefault();
        //a la soumission, on recupere les donnée du des champs par une technique de serialisation
                 var donnes_formulaire= $(this).serialize();
      //console.log( $( this ).serialize() );
   // alert(donnes_formulaire);  //on essai de visualiser notre metode de visualisation

                 var erreur_type='';
                  var erreur_salle='';
                  var erreur_reference='';
                  
         
              if($('.reference-salle').val()==''){
              erreur_reference='Entrez la refence de la salle';
              $('.erreur_reference').text(erreur_reference);
              $('.erreur_reference').css('color', 'red');
               $('.reference-salle').css('border-color', 'red');
              
          }else{
                 erreur_reference='';
               $('.erreur_reference').text(erreur_reference);
               $('.reference').css('border-color', 'black');
          }
          
          if($('.type-salle').val()==''){
              erreur_type='Entrez le type de la salle';
              $('.erreur_type').text(erreur_type);
              $('.erreur_type').css('color', 'red');
               $('.type-salle').css('border-color', 'red');
              
          }else{
                 erreur_type='';
               $('.erreur_type').text(erreur_type);
               $('.type-salle').css('border-color', 'black');
          }

          if($('.salle').val()==''){
              erreur_salle='Entrez le nom de la salle ';
              $('.erreur_salle').text(erreur_salle);
              $('.erreur_salle').css('color', 'red');
               $('.salle').css('border-color', 'red');
              
          }else{
                 erreur_salle='';
               $('.erreur_salle').text(erreur_salle);
               $('.salle').css('border-color', 'black');
          }
          
          if(erreur_salle!='' || erreur_reference!=''|| erreur_type!=''){
              
              return false;
          }else{
             
                    $.ajax({
                        type: 'POST',
                        data: donnes_formulaire,
                        url: "<?php echo $this->baseUrl(); ?>/site/salles/add",
                        success: function(data) {
                           alert(data);
                            if (data == 'OK')
                              alert("Enregistrement reussi");
                                //window.location.href = "<?php //echo $this->baseUrl(); ?>/site/site-region/list/p/<?php //echo $this->p; ?>/r/<?php //echo $this->r; ?>"
                        }
                    }); 

                }
    });
     






    $('#dataTable').DataTable({
            responsive: true,
            language: {
            searchPlaceholder: 'Rechercher...',
            sSearch: '',
            lengthMenu: '_MENU_',
        }
    });


    // Select2
    $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });

});
</script>

