<form method="post">
<div class="breadLine">
    <div class="breadCrumbsLeft">
        <ul>
            <li><a href="<?php echo $this->baseUrl(); ?>/"><i class="ti-home"></i> Home</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/site/dashboard">Dashboard</a></li>
            <li class="current"><a href="#"><?php echo $this->region['region']; ?></a></li>
        </ul>
    </div>
</div>

<div class="row row-sm">

    <div class="col-lg-9">
        
        <div class="card card-header tx-bold">
            SITES TECHNIQUE
        </div>
        <div class="card card-table-two">

            <table id="dataTable" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th class="wd-5p">N°Référence</th>
                    <th class="wd-15p">Site</th>
                    <th class="wd-5p">Type</th>
                    <th class="wd-5p">Ville / Commune / Quartier</th>
                    <th class="wd-5p">Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->sites as $u) :?>
                <tr class="">
                    <td class="bg-dark-"><span class="btn btn-danger tx-bold tx-white"><i class="fa fa-home"></i> <?php echo $u['reference']; ?></span></td>
                    <td class="bg-dark-"><span class="btn btn-primary tx-bold tx-white"><?php echo $u['site']; ?></span></td>
                    <td class="bg-dark-"><span class="btn btn-success tx-bold"><?php echo $u['type_site']; ?></span></td>
                    <td class="bg-dark-"><span class="btn btn-purple tx-bold"><?php echo $u['ville']." / ".$u['commune']." / ".$u['quartier']; ?></span></td>
                    <td class="bg-dark-">
                        <div dropdown="">
                            <span class="btn btn-dark dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-cog"></i> Actions <span class="caret"></span>
                            </span>
                            <div class="dropdown-menu">
                                <a href="<?php echo $this->baseUrl(); ?>/site/site-region/dossier/p/<?php echo $this->p; ?>/r/<?php echo $this->r; ?>/s/<?php echo $u['id']; ?>" class="dropdown-item">Voir les salles</a>
                                <a href="#" data-target="#edit-modal-<?php echo $u['id']; ?>" data-toggle="modal" class="dropdown-item">Modifier</a>
                                <a href="#" id="delete-<?php echo $u['id']; ?>" class="dropdown-item">Supprimer</a>
                            </div><!-- dropdown-menu -->
                        </div>
                    </td>
                </tr>

                    <div class="modal fade" id="edit-modal-<?php echo $u['id']; ?>" tabindex="-1" role="dialog" aria-hidden="true">
                    <form method="post" id="form-<?php echo $u['id']; ?>">
                    <div class="modal-dialog">
                        <div class="modal-content">

                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title"><strong>Site technique</strong></h4>
                            </div>

                            <div class="modal-body">
                                <div class="form-group">
                                    <label class="control-label">Libellé du site <span class="symbol required"></span></label>
                                    <input type="text" class="form-control" id="site-<?php echo $u['id']; ?>" value="<?php echo $u['site']; ?>" placeholder="Libellé du site" required="">
                                </div>
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-grey btn-o" data-dismiss="modal">Annuler</button>
                                <button type="button" id="edit-<?php echo $u['id']; ?>" class="btn btn-primary">Modifier</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

            <script>

                $('#edit-<?php echo $u['id']; ?>').on('click', function (e) {

                    e.preventDefault();
                    var id = '<?php echo $u['id'];?>';
                    var site = $('#site-<?php echo $u['id'];?>').val();

                    $.ajax({
                        type: 'POST',
                        data: 'id=' + id + '&site=' + site,
                        url: "<?php echo $this->baseUrl(); ?>/site/site-region/edit",
                        success: function (data) {
                            if (data == 'OK')
                                window.location.href = "<?php echo $this->baseUrl(); ?>/site/site-region/list/p/<?php echo $this->p; ?>/r/<?php echo $this->r; ?>"
                        }
                    });
                });


                $('#delete-<?php echo $u['id']; ?>').on('click', function (e) {

                    e.preventDefault();
                    var id = '<?php echo $u['id']; ?>';
                    swal({
                        title: "",
                        text: "Vous êtes sur le point de supprimer un enregistrement",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#d43f3a",
                        confirmButtonText: "continuer",
                        cancelButtonText: "annuler",
                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            type: 'POST',
                            data: 'id=' + id,
                            url: "<?php echo $this->baseUrl(); ?>/site/site-region/delete",
                            success: function (data) {
                                if (data == 'OK') {
                                    window.location.href = "<?php echo $this->baseUrl(); ?>/site/site-region/list/p/<?php echo $this->p; ?>/r/<?php echo $this->r; ?>"
                                }
                            }
                        });
                    });
                });

                </script>
                <?php endforeach; ?>
                </tbody>
          </table>      
        </div><!-- card-dashboard-five -->
    </div>


    <div class="col-lg-3">
        <div class="card card-header tx-bold">
            ENREGISTRER SITE TECHNIQUE
        </div>
        <div class="card card-table-two">  
            <div class="row row-sm">
                <div class="form-group col-12">
                    <label class="control-label">Ville <span class="symbol required"></span></label>
                    <select class="form-control select2-no-search" required name="ville" onchange="window.location ='<?php echo $this->baseUrl();?>/site/site-region/list/p/<?php echo $this->p;?>/r/<?php echo $this->r;?>/v/'+this.value">
                        <option value="">(Ville)</option>
                        <?php foreach ($this->villes as $v) :?>
                        <option value="<?php echo $v['id']; ?>" <?php echo ($v['id']==$this->v)?'selected':'';?>><?php echo $v['ville']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group col-12">
                    <label class="control-label">Commune <span class="symbol required"></span></label>
                    <select class="form-control select2-no-search" required name="commune" onchange="window.location ='<?php echo $this->baseUrl();?>/site/site-region/list/p/<?php echo $this->p;?>/r/<?php echo $this->r;?>/v/<?php echo $this->v;?>/c/'+this.value">
                        <option value="">(Commune)</option>
                        <?php foreach ($this->communes as $v) :?>
                        <option value="<?php echo $v['id']; ?>" <?php echo ($v['id']==$this->c)?'selected':'';?>><?php echo $v['commune']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group col-12">
                    <label class="control-label">Quartier <span class="symbol required"></span></label>
                    <select class="form-control select2-no-search" required name="quartier">
                        <option value="">(Quartier)</option>
                        <?php foreach ($this->quartiers as $v) :?>
                        <option value="<?php echo $v['id']; ?>"><?php echo $v['quartier']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group col-12">
                    <label class="control-label">Type de site <span class="symbol required"></span></label>
                    <select class="form-control select2-no-search" required name="type-site">
                        <option value="">(Type de site)</option>
                        <?php foreach ($this->types as $v) :?>
                        <option value="<?php echo $v['id']; ?>"><?php echo $v['type_site']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group col-12">
                    <label class="control-label">Référence du site</label>
                    <input type="text" name="reference-site" class="form-control tx-bold" value="SIT<?php echo strtoupper(substr(md5(date("YHismd")),0,8)); ?>">
                </div>
                <div class="form-group col-12">
                    <label class="control-label">Libellé du site</label>
                    <input type="text" name="site" class="form-control tx-bold" value="SITE SIT<?php echo strtoupper(substr(md5(date("YHismd")),0,8)); ?>">
                </div>
                <div class="form-group col-12">
                    <input type="submit" class="btn btn-squared btn-dark form-control" value="Enregistrer">
                </div>
            </div> 
        </div>
    </div>
    


</div>
</form>

<script>
$(document).ready(function(){
    'use strict';

    $('#dataTable').DataTable({
            responsive: true,
            language: {
            searchPlaceholder: 'Rechercher...',
            sSearch: '',
            lengthMenu: '_MENU_',
        }
    });


    // Select2
    $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });

});
</script>

