<div class="main-login col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
    <!-- start: LOGIN BOX -->
    <div class="box-login">
        <form class="form-login" method="post">
            <fieldset>
            <p align="center"><img src="<?php echo $this->baseUrl(); ?>/public/images/educatho.jpg" width="100%" height="50%"></p>
                <p><?php echo $this->message; ?></p>
                <div class="form-group">
                    <span class="input-icon">
                        <input type="text" class="form-control" name="username" placeholder="Identifiant">
                        <i class="fa fa-user"></i> 
                    </span>
                </div>
                <div class="form-group form-actions">
                    <span class="input-icon">
                        <input type="password" class="form-control password" name="password" placeholder="Mot de passe">
                        <i class="fa fa-lock"></i>
                    </span>
                </div>
                <div class="form-actions">
                    <button type="submit" class="form-control btn-squared btn-success text-bold">
                        Connectez-vous
                    </button>
                </div>
            </fieldset>
        </form>
        <!-- start: COPYRIGHT -->
        <div class="copyright">
            &copy; <span class="current-year"></span><span class="text-bold text-uppercase"> AKILI4DEV</span>
        </div>
        <!-- end: COPYRIGHT -->
    </div>
    <!-- end: LOGIN BOX -->
</div>