<?php  
if (!$this->balance){
    header("location:/metro-lab/certificat/eprouvette");
   exit();
}
require_once('library/tcpdf/tcpdf.php');  
$obj_pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);  
$obj_pdf->setCreator(PDF_CREATOR);  
$obj_pdf->setTitle("Certificat_de_balance");  
$obj_pdf->setHeaderData('', '', PDF_HEADER_TITLE, PDF_HEADER_STRING);  
$obj_pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));  
$obj_pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));  
$obj_pdf->setDefaultMonospacedFont('helvetica');  
$obj_pdf->setFooterMargin(PDF_MARGIN_FOOTER);  
$obj_pdf->setMargins(PDF_MARGIN_LEFT, '10', PDF_MARGIN_RIGHT);  
$obj_pdf->setPrintHeader(false);  
$obj_pdf->setPrintFooter(false);  
$obj_pdf->setAutoPageBreak(TRUE, 10);  
$obj_pdf->setFont('helvetica', '', 11);  
$obj_pdf->AddPage();  
$content = '';  

	# code...

  # code...

$content .= '  
<table border="0" >  
<tr>  
<th width="20%"><img src="public/images/logo-metrolab.png"   class="d-inline-block align-bottom mr-3" alt="Back to homepage" title="Back to homepage" width="80" height="30" loading="lazy"/> </th>  
<th width="40%"  style="color:black;font-size:0.6em; font-weight:bold;">METROLEB SARL Siege social Plateau dokui, non loin de la pharmacie Dokui. 21 BP 4776 Abidjan 21<br>
   Tel:(+225) 24002626 / 47711000 <br>sales@metroleb.com   www.metroleb.com
</th>  
<th width="20%">Logo partenaire</th>  
<th width="40%" style="color:black;font-weight:bold;">MEB/MET/001 <br> Version...</th>  
</tr>  
</table>
<br>

<div class=" text-center" style="border:2px solid black; border-radius:7px/8px ; text-align:center;">
   <span style="color:black;font-weight:bold;">CERTIFICAT D\'ETALONNAGE D\'EPROUVETTE GRADUEE</span>
   <br> <span>N°V/ '.$this->numero_certificat.'</span>
</div>
<br>
<span><b>DELIVRE A </b>: '.$this->balance['delivrance'].' </span>

<br>	
 
<h5 style="text-align:center;"> IDENTIFICATION DE L\'EQUIPEMENT</h5>
<br>

<table border="0"  style="font-size:0.7em; font-weight:bold;">  

<tr>  
<th width="30%">DESIGNATION:</th>
<td width="20%" > '.$this->balance['designation'].'</td>

<th width="30%">CAPACITE NOMINALE:</th> 
<td width="20%" > '.$this->balance['capacitenominale'].'</td> 
</tr>

<tr>
<th width="30%">MARQUE:</th>
<td width="20%" > '.$this->balance['marque'].'</td> 

<th width="30%" >N°METROLEB:</th> 
<td width="20%" >'.$this->balance['num_metroleb'].'</td> 
</tr>

<tr>
<th width="30%">LOCALISATION:</th> 
<td width="20%" >'. $this->balance['localisation'].'</td> 
<th width="30%" > </th> 
<td width="20%" > </td> 
</tr>

<tr>
<th width="30%" >DATE D\'EMISSION:</th> 
<td width="20%" > '. $this->balance['date_emission'].'</td> 

<th width="30%" >CLASSE:</th> 
<td width="20%" >'. $this->balance['classe'].' </td> 
</tr>

<tr>
<th width="30%" > </th> 
<td width="20%" > </td>

<th width="30%" > </th> 
<td width="20%" ></td>  
</tr>

</table>



<h5 style="text-align:center;">METHODE DE MESURE</h5>


<span style="font-size:0.8em;">Nombre de pesees individuelle : '. $this->balance['nb_pesees'].' 
</span>


<h5 style="text-align:center;">MOYENS DE MESURE</h5>


<span style="font-size:0.8em;">Masses étalons : '. $this->balance['masse_etalons'].' </span>

<br><br>

<span style="font-size:0.8em;">Thermometre Etalon N°CE: '. $this->balance['thermometre'].' </span>


  <h5 style="text-align:center;">CONDITION DE MESURE  </h5>



<span style="font-size:0.8em;">Ces mesures ont été effectuées sur site </span>
<br><br>
<span style="font-size:0.8em;">Eau distillée à :'. $this->balance['eau_distillee'].' </span>
<br>
<br>
<span style="font-size:0.8em;"> Z(Facteur de correction)='.$this->balance['facteur_correction'].' uL/mg </span>

           <h5 style="text-align:center;"> TABLEAU DE RESULTAT </h5>
  
   EMT:+_ .......mL <br>
            <table border="1"  style="text-align:center; font-size:0.8em; font-weight:bold; ">

              <tr >
    <th>N° de pesee</th>  <th>Quantité mesurée avec l\'éprouvette X(ml)</th>  <th>Volume correspondant au poids mesure Cm (mL)</th>  <th>Ecarts</th> <th>Incertitude</th>
              </tr>
<tr>
    <td>'. $this->balance['ps1'].'</td>
     <td>'. $this->balance['qm1'].'</td>
     <td>'.$this->balance['vc1'].'</td>
     <td >'. $this->balance['ecart1'].'</td>

      <td >'. round($this->balance['incert1'],3).' </td>
</tr>

<tr>
     <td>'. $this->balance['ps2'].'</td>
     <td>'. $this->balance['qm2'].'</td>
     <td>'.$this->balance['vc2'].'</td>
     <td >'. $this->balance['ecart2'].'</td>

      <td >'. round($this->balance['incert2'],3).' </td>
</tr>
<tr>
     <td>'. $this->balance['ps3'].'</td>
     <td>'. $this->balance['qm3'].'</td>
     <td>'.$this->balance['vc3'].'</td>
     <td >'. $this->balance['ecart3'].'</td>

      <td >'. round($this->balance['incert3'],3).' </td>
</tr>
<tr>
     <td>'. $this->balance['ps4'].'</td>
     <td>'. $this->balance['qm4'].'</td>
     <td>'.$this->balance['vc4'].'</td>
     <td >'. $this->balance['ecart4'].'</td>

      <td >'. round($this->balance['incert4'],3).' </td>
</tr>
<tr>
     <td>'. $this->balance['ps5'].'</td>
     <td>'. $this->balance['qm5'].'</td>
     <td>'.$this->balance['vc5'].'</td>
     <td >'. $this->balance['ecart5'].'</td>

      <td >'. round($this->balance['incert5'],3).' </td>
</tr>
<tr>
     <td>'. $this->balance['ps6'].'</td>
     <td>'. $this->balance['qm6'].'</td>
     <td>'.$this->balance['vc6'].'</td>
     <td >'. $this->balance['ecart6'].'</td>

      <td >'. round($this->balance['incert6'],3).' </td>
</tr>
<tr>
     <td>'. $this->balance['ps7'].'</td>
     <td>'. $this->balance['qm7'].'</td>
     <td>'.$this->balance['vc7'].'</td>
     <td >'. $this->balance['ecart7'].'</td>

      <td >'. round($this->balance['incert7'],3).' </td>
</tr>
<tr>
     <td>'. $this->balance['ps8'].'</td>
     <td>'. $this->balance['qm8'].'</td>
     <td>'.$this->balance['vc8'].'</td>
     <td >'. $this->balance['ecart8'].'</td>

      <td >'. round($this->balance['incert8'],3).' </td>
</tr>

  </table>
<br>
Cm=X.Z avec X=Valeur nominale des pesées effectuées
  <br>  <br>
<b>Prochain etalonnage: '.$this->balance["date_etalonnage"].'</b>

   

<br><br>
<table border="0">
<tr >
<td width="60%" style="font-weight:bold; font-size:1em">Etalonnage réalisé par: </td> <td width="40%" style="text-align:right;font-weight:bold; font-size:1em;">Service Metrologie : </td>
</tr>
</table>

<br><br><br><br><br><br> <br>
<p style="text-align:center; font-size:0.8em; font-weight:bold;" > La reproduction de ce document n\'est  autorisée que sous forme de fac-similé photographique integrale. Ce certificat est conforme au fascicule de documentation FD X 07-012 <p>
  
';  
 


$obj_pdf->writeHTML($content);  
$obj_pdf->Output('Certificat eprouvette graduee.pdf', 'D');  

?>