<div class="breadLine">
    <div class="breadCrumbsLeft">
        <ul>
            <li><a href="<?php echo $this->baseUrl(); ?>/principal/dashboard"><i class="ti-home"></i> Dashboard</a></li>
            <li class="current"><a href="#">Utilisateurs école</a></li>
        </ul>
    </div>
</div>

<h2 class="az-content-title tx-24 mg-b-5">
    <div dropdown="">
        <span class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-cog"></i> UTILISATEURS ECOLE <span class="caret"></span>
        </span>
        <div class="dropdown-menu">
            <a href="#" data-target="#add-modal" data-toggle="modal" class="dropdown-item">Ajouter un utilisateur</a>
        </div><!-- dropdown-menu -->
    </div>
</h2>

<p class="mg-b-20 mg-lg-b-25">Liste des utilisateurs du module école</p>

<div class="row row-sm">

    <div class="col-lg-8">
        <div class="card card-table-two">

            <div class="table-responsive">
            <table id="dataTable" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th class="wd-5p">Utilisateur</th>
                <th class="wd-5p">Identifiant</th>
                <th class="wd-5p">Groupe</th>
                <th class="wd-5p">Ecole</th>
                <th class="wd-5p">Actions</th>
              </tr>
            </thead>
            <tbody>
                <?php foreach ($this->users as $u) :?>
              <tr class="">
                <td class=""><span class="btn btn-dark tx-bold"><?php echo $u['administrateur']; ?></span></td>
                <td class=""><span class="btn btn-primary"><?php echo $u['login']; ?></span></td>
                <td class=""><span class="btn btn-primary"><?php echo $u['groupe']; ?></span></td>
                <td class=""><span class="btn btn-primary"><?php echo $u['ecole']; ?></span></td>
                <td>
                <div dropdown="">
                        <span class="btn btn-dark dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            <i class="fa fa-cog"></i> Actions <span class="caret"></span>
                        </span>
                        <div class="dropdown-menu">
                            <a href="#" data-target="#edit-modal-<?php echo $u['id']; ?>" data-toggle="modal" class="dropdown-item">Modifier</a>
                            <a href="#" id="delete-<?php echo $u['id']; ?>" class="dropdown-item">Supprimer</a>
                        </div><!-- dropdown-menu -->
                    </div>
                </td>
              </tr>
              
            
            <div class="modal fade" id="edit-modal-<?php echo $u['id']; ?>" tabindex="-1" role="dialog" aria-hidden="true">
                <form method="post" id="form-<?php echo $u['id']; ?>">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title"><strong>Utilisateur école</strong></h4>
                        </div>

                        <div class="modal-body">
                            <div class="form-group">
                                <label class="control-label">Nom & prénoms <span class="symbol required"></span></label>
                                <input type="text" class="form-control" id="administrateur-<?php echo $u['id']; ?>" value="<?php echo $u['administrateur']; ?>" placeholder="Nom & prénoms" required="">
                            </div>
                            <div class="form-group">
                                <label class="control-label">Identifiant <span class="symbol required"></span></label>
                                <input type="text" class="form-control" id="login-<?php echo $u['id']; ?>" value="<?php echo $u['login']; ?>" placeholder="Identifiant" required="">
                            </div>
                            <div class="form-group">
                                <label class="control-label">Groupe utilisateur <span class="symbol required"></span></label>
                                <select class="form-control" id="groupe-<?php echo $u['id']; ?>" required="">
                                    <option value="">(Choisissez un groupe d'utilisateur)</option>
                                    <?php foreach ($this->groupes as $g) :?>
                                    <option value="<?php echo $g['id'];?>" <?php if($u['id_groupe']==$g['id'])echo 'selected';?>><?php echo $g['groupe'];?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Etablissement <span class="symbol required"></span></label>
                                <select class="form-control" id="ecole-<?php echo $u['id']; ?>" required="">
                                    <option value="">(Choisissez un établissement)</option>
                                    <?php foreach ($this->ecoles as $g) :?>
                                    <option value="<?php echo $g['id'];?>" <?php if($u['id_ecole']==$g['id'])echo 'selected';?>><?php echo $g['ecole'];?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-grey btn-o" data-dismiss="modal">Annuler</button>
                            <button type="button" id="edit-<?php echo $u['id']; ?>" class="btn btn-primary">Modifier</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <script>

            $('#edit-<?php echo $u['id']; ?>').on('click', function (e) {

                e.preventDefault();
                var id = '<?php echo $u['id'];?>';
                var administrateur = $('#administrateur-<?php echo $u['id'];?>').val();
                var login = $('#login-<?php echo $u['id'];?>').val();
                var groupe = $('#groupe-<?php echo $u['id'];?>').val();
                var ecole = $('#ecole-<?php echo $u['id'];?>').val();

                $.ajax({
                    type: 'POST',
                    data: 'id=' + id + '&administrateur=' + administrateur + '&login=' + login + '&groupe=' + groupe + '&ecole=' + ecole,
                    url: "<?php echo $this->baseUrl(); ?>/principal/user/edit",
                    success: function (data) {
                        if (data == 'OK')
                            window.location.href = "<?php echo $this->baseUrl(); ?>/principal/user/list"
                    }
                });
            });


            $('#delete-<?php echo $u['id']; ?>').on('click', function (e) {

                e.preventDefault();
                var id = '<?php echo $u['id']; ?>';
                swal({
                    title: "",
                    text: "Vous êtes sur le point de supprimer un enregistrement",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#d43f3a",
                    confirmButtonText: "continuer",
                    cancelButtonText: "annuler",
                    closeOnConfirm: false
                }, function () {
                    $.ajax({
                        type: 'POST',
                        data: 'id=' + id,
                        url: "<?php echo $this->baseUrl(); ?>/principal/user/delete",
                        success: function (data) {
                            if (data == 'OK') {
                                window.location.href = "<?php echo $this->baseUrl(); ?>/principal/user/list"
                            }
                        }
                    });
                });
            });

            </script>
              <?php endforeach; ?>
            </tbody>
          </table>      
            </div><!-- table-responsive -->
        </div><!-- card-dashboard-five -->
    </div>


</div>

<div class="modal fade parsley-style-1" id="add-modal" tabindex="-1" role="dialog" aria-hidden="true">

    <form role="form" id="form">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title"><strong>Utilisateur école</strong></h4>
                </div>

                <div class="modal-body">

                    <div class="form-group">
                        <label class="control-label">Nom  prénoms <span class="tx-danger">*</span></label>
                        <input type="text" class="form-control" id="administrateur" placeholder="Nom & prénoms" required="">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Identifiant <span class="symbol required"></span></label>
                        <input type="text" class="form-control" id="login" placeholder="Identifiant" required="">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Groupe utilisateur <span class="symbol required"></span></label>
                        <select class="form-control" id="groupe" required="">
                            <option value="">(Choisissez un groupe d'utilisateur)</option>
                            <?php foreach ($this->groupes as $g) :?>
                            <option value="<?php echo $g['id'];?>"><?php echo $g['groupe'];?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Etablissement <span class="symbol required"></span></label>
                        <select class="form-control" id="ecole" required="">
                            <option value="">(Choisissez un établissement)</option>
                            <?php foreach ($this->ecoles as $g) :?>
                            <option value="<?php echo $g['id'];?>"><?php echo $g['ecole'];?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-grey btn-o" data-dismiss="modal">Annuler</button>
                    <button type="button" name="add" id="add" class="btn btn-primary">Ajouter</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
$(document).ready(function(){
    'use strict';

    $('#add').on('click', function (e) {
    
    e.preventDefault();
    var administrateur = $('#administrateur').val();
    var login = $('#login').val();
    var groupe = $('#groupe').val();
    var ecole = $('#ecole').val();

    //$('#form').parsley();

    $.ajax({
        type: 'POST',
        data: 'administrateur=' + administrateur + '&login=' + login + '&groupe=' + groupe + '&ecole=' + ecole,
        url: "<?php echo $this->baseUrl(); ?>/principal/user/add",
        success: function (data) {
            if (data == 'OK') {
                window.location.href = "<?php echo $this->baseUrl(); ?>/principal/user/list";
            }
        }
    });
});

    $('#dataTable').DataTable({
            responsive: true,
            language: {
            searchPlaceholder: 'Rechercher...',
            sSearch: '',
            lengthMenu: '_MENU_',
        }
    });


    // Select2
    $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });

});
</script>

