<section id="page-title" class="padding-top-15 padding-bottom-15">
    <div class="row">

        <div class="col-sm-10">
            <h1 class="mainTitle">Groupes utilisateurs</h1>
            <span class="mainDescription">Liste des groupes d'habilitation</span>
        </div>
        <?php if($this->user['module'][2]['system_1']['add']== 1):?>
        <div class="col-sm-2">
            <ul class="mini-stats pull-right">
                <li>
                    <a href="#" data-toggle="modal" data-target="#add-modal">
                    <span class="fa-stack fa-2x"> 
                        <i class="fa fa-circle fa-stack-2x text-dark"></i> 
                        <i class="fa fa-plus fa-stack-1x fa-inverse"></i> 
                    </span>
                    <p class="text-small text-dark no-margin">
                        Ajouter
                    </p>
                    </a>
                </li>
            </ul>
        </div>
        <?php endif;?> 
    </div>
</section>

<div class="breadLine">
    <div class="breadCrumbsLeft">
        <ul>
            <li><a href="<?php echo $this->baseUrl(); ?>/system/dashboard"><i class="ti-home"></i> Dashboard</a></li>
            <li class="current"><a href="#">Groupe utilisateurs</a></li>
        </ul>
    </div>
</div>


<div class="container-fluid container-fullw padding-bottom-10">
    <div class="row">


        <div class="col-sm-12">
            <div class="row">

                <div class="col-md-7 col-lg-12">
                    <div class="panel panel-white no-radius" id="visits">
                        <div class="panel-heading border-light">
                            <h4 class="panel-title"> Liste des groupes d'utilisateurs' </h4>
                        </div>

                        <div collapse="visits" class="panel-wrapper">
                            <div class="panel-body">

                                <div class="table-responsive col-md-12">
                                    <table class="table table-striped table-bordered table-hover" id="dataTable">
                                        <thead>
                                            <tr>
                                                <th>Groupe</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            <?php foreach ($this->groupes as $u) :?>

                                                <tr>
                                                    <td><span class="btn btn-squared btn-grey text-dark"><?php echo $u['groupe']; ?></span></td>
                                                    <td>
                                                        <a href="<?php echo $this->baseUrl();?>/system/groupe/module/id/<?php echo $u['id']; ?>" class="btn btn-squared btn-dark-blue"><i class="fa fa-list"></i></a>
                                                        <?php if($this->user['module'][2]['system_1']['edit']== 1):?>
                                                        <a href="#" class="btn btn-squared btn-primary" data-toggle="modal" data-target="#edit-modal-<?php echo $u['id']; ?>"><i class="fa fa-pencil"></i></a>
                                                        <?php endif;?>
                                                        <?php if($this->user['module'][2]['system_1']['del']== 1):?>
                                                        <a href="#" class="btn btn-squared btn-danger" id="delete-<?php echo $u['id']; ?>"><i class="fa fa-trash"></i></a>
                                                        <?php endif;?>
                                                        <input type="hidden" id="id-<?php echo $u['id']; ?>" value="<?php echo $u['id']; ?>"/>
                                                    </td>
                                                </tr>

                                            <div class="modal fade" id="edit-modal-<?php echo $u['id']; ?>" tabindex="-1" role="dialog" aria-hidden="true">
                                                <form method="post" id="form-<?php echo $u['id']; ?>">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                                <h4 class="modal-title"><strong>Modification groupe</strong></h4>
                                                            </div>

                                                            <div class="modal-body">

                                                                <div class="form-group">
                                                                    <label class="control-label">Groupe utilisateur <span class="symbol required"></span></label>
                                                                    <input type="text" class="form-control" id="groupe-<?php echo $u['id']; ?>" value="<?php echo $u['groupe']; ?>" placeholder="Groupe utilisateur" required="">
                                                                </div>

                                                            </div>

                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-primary btn-o" data-dismiss="modal">Annuler</button>
                                                                <button type="button" id="edit-<?php echo $u['id']; ?>" class="btn btn-primary">Enregistrer</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>

                                            <script>


                                                $('#edit-<?php echo $u['id']; ?>').on('click', function (e) {

                                                    e.preventDefault();
                                                    var id = $('#id-<?php echo $u['id']; ?>').val();
                                                    var groupe = $('#groupe-<?php echo $u['id']; ?>').val();

                                                    if (!$('#form-<?php echo $u['id']; ?>').valid())
                                                        return false;

                                                    $.ajax({
                                                        type: 'POST',
                                                        data: 'id=' + id + '&groupe=' + groupe,
                                                        url: "<?php echo $this->baseUrl(); ?>/system/groupe/edit",
                                                        success: function (data) {
                                                            if (data == 'OK')
                                                                window.location.href = "<?php echo $this->baseUrl(); ?>/system/groupe/list"
                                                        }
                                                    });
                                                });


                                                
                                                
                                                $('#delete-<?php echo $u['id']; ?>').on('click', function (e) {

                                                    e.preventDefault();
                                                    var id = $('#id-<?php echo $u['id']; ?>').val();
                                                    swal({
                                                        title: "",
                                                        text: "Vous êtes sur le point de supprimer un enregistrement",
                                                        type: "warning",
                                                        showCancelButton: true,
                                                        confirmButtonColor: "#007AFF",
                                                        confirmButtonText: "continuer",
                                                        cancelButtonText: "annuler",
                                                        closeOnConfirm: false
                                                    }, function () {

                                                        $.ajax({
                                                            type: 'POST',
                                                            data: 'id=' + id,
                                                            url: "<?php echo $this->baseUrl(); ?>/system/groupe/delete",
                                                            success: function (data) {

                                                                if (data == 'OK') {
                                                                    window.location.href = "<?php echo $this->baseUrl(); ?>/system/groupe/list"
                                                                }
                                                            }
                                                        });
                                                    });
                                                });

                                            </script>


                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>


                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>

    </div>
</div>
<div class="modal fade" id="add-modal" tabindex="-1" role="dialog" aria-hidden="true">

    <form role="form" id="form">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title"><strong>Nouveau groupe</strong></h4>
                </div>

                <div class="modal-body">

                    <div class="form-group">
                        <label class="control-label">Groupe utilisateur <span class="symbol required"></span></label>
                        <input type="text" class="form-control" id="groupe" placeholder="Groupe utilisateur" required="">
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary btn-o" data-dismiss="modal">Annuler</button>
                    <button type="button" name="add" id="add" class="btn btn-primary">Enregistrer</button>
                </div>
            </div>
        </div>
    </form>
</div>


<script src="<?php echo $this->baseUrl(); ?>/private/vendor/select2/select2.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/private/vendor/DataTables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/private/vendor/sweetalert/sweet-alert.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/private/vendor/jquery-validation/jquery.validate.min.js"></script>


<script>
                                                /* Data table */
                                                var TableData = function () {
                                                    "use strict";
                                                    var runDataTable = function () {

                                                        $('#add').on('click', function (e) {
                                                            e.preventDefault();
                                                            var groupe = $('#groupe').val();

                                                            $('#form').validate({
                                                                errorElement: "span", // contain the error msg in a span tag
                                                                errorClass: 'help-block',
                                                                errorPlacement: function (error, element) { // render error placement for each input type
                                                                    if (element.attr("type") == "radio" || element.attr("type") == "checkbox") { // for chosen elements, need to insert the error after the chosen container
                                                                        error.insertAfter($(element).closest('.form-group').children('div').children().last());
                                                                    } else {
                                                                        error.insertAfter(element);
                                                                        // for other inputs, just perform default behavior
                                                                    }
                                                                },
                                                                ignore: "",
                                                                highlight: function (element) {
                                                                    $(element).closest('.help-block').removeClass('valid');
                                                                    // display OK icon
                                                                    $(element).closest('.form-group').removeClass('has-success').addClass('has-error').find('.symbol').removeClass('ok').addClass('required');
                                                                    // add the Bootstrap error class to the control group
                                                                },
                                                                unhighlight: function (element) { // revert the change done by hightlight
                                                                    $(element).closest('.form-group').removeClass('has-error');
                                                                    // set error class to the control group
                                                                },
                                                            });

                                                            if (!$('#form').valid())
                                                                return false;

                                                            $.ajax({
                                                                type: 'POST',
                                                                data: 'groupe=' + groupe,
                                                                url: "<?php echo $this->baseUrl(); ?>/system/groupe/add",
                                                                success: function (data) {
                                                                    if (data == 'OK') {
                                                                        window.location.href = "<?php echo $this->baseUrl(); ?>/system/groupe/list";
                                                                    }
                                                                }
                                                            });
                                                        });



                                                        var oTable = $('#dataTable').dataTable({
                                                            "aoColumnDefs": [{
                                                                    "aTargets": [0]
                                                                }],
                                                            "oLanguage": {
                                                                "sLengthMenu": "_MENU_ lignes",
                                                                "sSearch": "",
                                                                "sSearchPlaceholder": "Rechercher",
                                                                "sInfo": "_START_ - _END_ / _TOTAL_",
                                                                "sInfoEmpty": "0 - _END_ / _TOTAL_",
                                                                "sInfoFiltered": " trouvé(s) sur _MAX_ enregistrement(s)",
                                                                "sZeroRecords": "Aucune donnée disponible",
                                                                "sPaginationType": "bootstrap",
                                                                "oPaginate": {
                                                                    "sPrevious": '',
                                                                    "sNext": '',
                                                                }
                                                            },
                                                            "ordering": true,
                                                            "searching": true,
                                                            "bFilter": true,
                                                            "bLengthChange": true,
                                                            //"aaSorting": [[0, 'desc']],
                                                            "order": [[0, "asc"]],
                                                            "aLengthMenu": [[10, 15, 20, -1], [10, 15, 20, "Tout"]],
                                                            // set the initial value
                                                            "iDisplayLength": 10,
                                                        });

                                                        $('.dataTables_filter input').addClass("form-control input-sm").attr({"placeholder": "Rechercher", "size": "40px"});
                                                        $('.dataTables_length select').addClass("m-wrap small");
                                                        $('.dataTables_length select').select2();
                                                        $('input[type="checkbox"]').change(function () {
                                                            var iCol = parseInt($(this).attr("data-column"));
                                                            var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
                                                            oTable.fnSetColumnVis(iCol, (bVis ? false : true));
                                                        });

                                                    };

                                                    return{
                                                        init: function () {
                                                            runDataTable();
                                                        }
                                                    };

                                                }();

                                                jQuery(document).ready(function () {
                                                    TableData.init();
                                                });
</script>