<link href="<?php echo $this->baseUrl(); ?>/private/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
<link href="<?php echo $this->baseUrl(); ?>/private/azia/lib/select2/css/select2.min.css" rel="stylesheet">

<div class="breadLine">
    <div class="breadCrumbsLeft">
        <ul>
            <li><a href="<?php echo $this->baseUrl(); ?>/principal/dashboard"><i class="ti-home"></i> Dashboard</a></li>
            <li class="current"><a href="#">Traiter les élèves</a></li>
        </ul>
    </div>
</div>

<h2 class="az-content-title tx-24 mg-b-5">TRAITEMENT DES ELEVES</h2>
<p class="mg-b-20 mg-lg-b-25">Boîte à outils pour suivre les élèves</p>



<div class="row row-sm">

    <div class="col-lg-2 mg-b-20">

        <div class="card card-table-two">
            <div class="az-content-label mg-b-5 text-center">ANOMALIE DETECTEE</div>
            <div class="row row-sm">
                <div class="form-group col-12">
                    <div class="panel-body height-150 text-center">
                        <h1 class="fa fa-5x text-dark text-bold"><?php echo number_format(sizeof($this->result));?></h1>
                    </div>
                    <label class="control-label text-center">Elèves n'ayant pas été affecté à un établissement</label>
                </div>
            </div><!-- row -->
            <div class="card-footer-">
                <?php if(sizeof($this->result)):?>
                <div dropdown="" align="right">
                    <span class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-cog"></i> Actions <span class="caret"></span>
                    </span>
                    <div class="dropdown-menu">
                        <a href="#" class="dropdown-item" id="deleteEleveEcole">Supprimer les élèves sans école</a>
                    </div><!-- dropdown-menu -->
                </div>
                <?php endif;?>
            </div>
        </div><!-- card-dashboard-five -->

    </div>


    <div class="col-lg-5 mg-b-20">

        <form method="post" enctype="multipart/form-data">
        <div class="card card-table-two">
            <div class="az-content-label mg-b-5">FICHIER ELEVE</div>
                
            <div class="row row-sm">

                <div class="form-group col-12"><?php echo $this->message;?></div>
                <div class="form-group col-12">
                    <label class="control-label">Etablissement <span class="symbol required"></span></label>
                    <select class="form-control" name="ecole" id="ecole" required="" onchange="if (this.value) window.location.href='<?php echo $this->baseUrl();?>/principal/sandbox/eleve/id/'+this.value">
                        <option value="">(Choisissez une école)</option>
                        <?php foreach ($this->ecoles as $e) : ?>
                        <option value="<?php echo $e['id']; ?>" <?php if($e['id']==$this->id)echo 'selected';?>><?php echo $e['ecole']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group col-6">
                    <label class="control-label">Année scolaire <span class="symbol required"></span></label>
                    <select class="form-control" name="annee" id="annee" required="">
                        <option value="">(Choisissez une année scolaire)</option>
                        <?php foreach ($this->annees as $a) : ?>
                        <option value="<?php echo $a['id']; ?>" <?php if($a['id']==$this->user['id-annee'])echo 'selected';?>><?php echo $a['annee']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group col-6">
                    <label class="control-label">Niveau d'étude <span class="symbol required"></span></label>
                    <select class="form-control" name="niveau" id="niveau" required="" onchange="if (this.value) window.location.href='<?php echo $this->baseUrl();?>/principal/sandbox/eleve/id/<?php echo $this->id;?>/nv/'+this.value">
                        <option value="">(Choisissez un niveau d'étude)</option>
                        <?php foreach ($this->niveaux as $n) : ?>
                        <option value="<?php echo $n['id_niveau']; ?>" <?php if($n['id_niveau']==$this->nv)echo 'selected';?>><?php echo $n['niveau'].' '.$n['serie']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group col-6">
                    <label class="control-label">Classe <span class="symbol required"></span></label>
                    <select class="form-control" name="classe" id="classe">
                        <option value="">(Choisissez une classe)</option>
                        <?php foreach ($this->classes as $n) : ?>
                        <option value="<?php echo $n['id']; ?>"><?php echo $n['classe']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group col-6">
                    <label class="control-label">Statut <span class="symbol required"></span></label>
                    <select class="form-control" name="type" id="type" required="">
                        <option value="">(Choisissez un statut)</option>
                        <option value="1">NON AFFECTE</option>
                        <option value="2">AFFECTE</option>
                    </select>
                </div>
                
                <div class="form-group col-12">
                    <label class="control-label">Fichier élève <span class="symbol required"></span></label>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="customFile" name="fichier" required>
                        <label class="custom-file-label" for="customFile">Choix fichier</label>
                    </div>
                </div>
                <div class="form-group col-12">
                    <input type="submit" name="valider-import" class="btn btn-squared btn-primary form-control" value="Enregistrer les effectifs">
                </div>

            </div><!-- row -->
            <div class="card-footer bg-primary-">
                <div dropdown="" align="right">
                    <span class="dropdown-toggle tx-bold" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-cog"></i> Actions <span class="caret"></span>
                    </span>
                    <div class="dropdown-menu">
                        <a href="#" class="dropdown-item" id="deleteEleve">Annulation importation des élèves</a>
                    </div><!-- dropdown-menu -->
                </div>
            </div>
        </div><!-- card-dashboard-five -->
        <form>

    </div>



    <div class="col-lg-4 mg-b-20">

        <div class="card card-table-two">
            <div class="az-content-label mg-b-5">MODE D'EMPLOI</div>
            <p class="mg-b-20">Instructions d'utilisation</p>
                
            <div class="row row-sm">

                <div class="form-group col-12">
                    Fichier: <b>xls,xlsx</b><br>
                    Format du fichier:
                    <b>MATRICULE;Nom;Prénoms;Sexe;CNI/N°Extrait Naissance;Taux de réduction;Nom du père;Téléphone du père;Nom de la mère;Téléphone de la mère;Fichier Image</b><br>
                    Exemple:16-0012-EDU;KPAN;YVES;H;MAN-001-2005;35;KPAN GEORGES;0999999;YAO JEANNE;0888888;16-0012-EDU.png
                                

                </div>

            </div><!-- row -->
        </div><!-- card-dashboard-five -->

    </div>


    

    

</div>



<script src="<?php echo $this->baseUrl(); ?>/private/azia/lib/jquery/jquery.min.js"></script>

<script src="<?php echo $this->baseUrl(); ?>/private/vendor/sweetalert/sweet-alert.min.js"></script>

<script>

        $('#deleteEleve').on('click', function (e) {

            e.preventDefault();
            var annee = $('#annee').val();
            var ecole = $('#ecole').val();
            var type = $('#type').val();
            var niveau = $('#niveau').val();
            var classe = $('#classe').val();

            if(!annee){

                swal({
                title: "",
                text: "Veuillez choisir au moins une année scolaire",
                type: "info",
                showCancelButton: true,
                confirmButtonColor: "#007AFF",
                confirmButtonText: "continuer",
                cancelButtonText: "annuler",
                closeOnConfirm: false
            }, function () {
                window.location.href = "<?php echo $this->baseUrl(); ?>/system/import/eleve"
            });

            }
            else{
                swal({
                title: "",
                text: "Vous êtes sur le point de supprimer une liste d'élèves. \nCette action peut entraîner la perte de données sensibles",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#d43f3a",
                confirmButtonText: "continuer",
                cancelButtonText: "annuler",
                closeOnConfirm: false
            }, function () {

                swal({
                    title: "",
                    text: "En cours de traitement...",
                    type: "info",
                    showConfirmButton: false,
                }),
                $.ajax({
                    type: 'POST',
                    data: 'annee=' + annee + '&ecole=' + ecole + '&type=' + type + '&niveau=' + niveau + '&classe=' + classe,
                    url: "<?php echo $this->baseUrl(); ?>/principal/sandbox/delete-eleve",
                    success: function (data) {

                        if (data == 'OK') {
                            window.location.href = "<?php echo $this->baseUrl(); ?>/principal/sandbox/eleve"
                        }
                    }
                });
            });
            }
            
        });


        $('#deleteEleveEcole').on('click', function (e) {

            e.preventDefault();
            
            swal({
                title: "",
                text: "Vous allez supprimer une liste d'élèves sans école. \nCette action peut entraîner la perte de données sensibles",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#d43f3a",
                confirmButtonText: "continuer",
                cancelButtonText: "annuler",
                closeOnConfirm: false
            }, function () {

                swal({
                    title: "",
                    text: "En cours de traitement...",
                    type: "info",
                    showConfirmButton: false,
                }),
                $.ajax({
                    type: 'POST',
                    url: "<?php echo $this->baseUrl(); ?>/principal/sandbox/delete-eleve-ecole",
                    success: function (data) {

                        if (data == 'OK') {
                            window.location.href = "<?php echo $this->baseUrl(); ?>/principal/sandbox/eleve"
                        }
                    }
                });
            });
            
        });
</script>
