<?php  
function fetch_data()  
{  
  
     
$output = '<tr>  
<td>1</td>  
<td>GALOGBE</td>  
<td>Fernandaize</td>  
<td>galogbe@ingenieur.com</td>  
</tr>  
';  
  
return $output;  
}  

require_once('library/tcpdf/tcpdf.php');  
$obj_pdf = new TCPDF('P', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);  
$obj_pdf->SetCreator(PDF_CREATOR);  
$obj_pdf->SetTitle("Generate HTML Table Data To PDF From MySQL Database Using TCPDF In PHP");  
$obj_pdf->SetHeaderData('', '', PDF_HEADER_TITLE, PDF_HEADER_STRING);  
$obj_pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));  
$obj_pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));  
$obj_pdf->SetDefaultMonospacedFont('helvetica');  
$obj_pdf->SetFooterMargin(PDF_MARGIN_FOOTER);  
$obj_pdf->SetMargins(PDF_MARGIN_LEFT, '10', PDF_MARGIN_RIGHT);  
$obj_pdf->setPrintHeader(false);  
$obj_pdf->setPrintFooter(false);  
$obj_pdf->SetAutoPageBreak(TRUE, 10);  
$obj_pdf->SetFont('helvetica', '', 11);  
$obj_pdf->AddPage();  
$content = '';  
$content .= '  

<table border="0" >  
<tr>  
<th width="20%"><img src="public/images/logo-metrolab.png"   class="d-inline-block align-bottom mr-3" alt="Back to homepage" title="Back to homepage" width="80" height="30" loading="lazy"/> </th>  
<th width="40%"  style="color:black;font-size:0.6em; font-weight:bold;">METROLEB SARL Siege social Plateau dokui, non loin de la pharmacie Dokui. 21 BP 4776 Abidjan 21<br>
   Tel:(+225) 24002626 / 47711000 <br>sales@metroleb.com   www.metroleb.com
</th>  
<th width="20%">Logo partenaire</th>  
<th width="40%" style="color:black;font-weight:bold;">MEB/MET/001 <br> Version...</th>  
</tr>  
</table>
<br>

<div class=" text-center" style="border:2px solid black; border-radius:7px/8px ; text-align:center; ">
   <span style="color:black;font-weight:bold;">CERTIFICAT D\'ETALONNAGE DE BALANCE</span>
   <br> <span>N° B...... -......-......</span>
</div>
<br>
<span><b>DELIVRE A </b>:  </span>

<br>	

 
<div  style="text-align:center;font-weight:bolder; font-size:0.7em;"><u>INSTRUMENT ETALONNE</u></div>
<br>

<table border="0"  style="font-size:0.7em;">  



<tr>  
<th width="30%">DESIGNATION:</th>
<td width="20%" >  </td>

<th width="30%" >DATE D\'ETALONNAGE:</th> 
<td width="20%" > </td> 
</tr>

<tr>
<th width="30%">MODELE:</th>
<td width="20%" > </td> 

<th width="30%" >PORTEE MINI-MAX:</th> 
<td width="20%" > </td> 
</tr>

<tr>
<th width="30%">LOCALISATION DU MATERIEL:</th> 
<td width="20%" > </td> 
<th width="30%" >ECHELLON:</th> 
<td width="20%" > </td> 
</tr>

<tr>
<th width="30%" >N°LBTP:</th> 
<td width="20%" > </td> 

<th width="30%" >N°METROLEB:</th> 
<td width="20%" > </td> 
</tr>

<tr>
<th width="30%" >CLASSE:</th> 
<td width="20%" > </td>

<th width="30%" >TYPE:</th> 
<td width="20%" > </td>  
</tr>

<tr>
<th width="30%" >N°SERIE</th> 
<td width="20%" > </td> 

<th width="30%" >DATE DU PROCHAIN ETALONNAGE:</th> 
<td width="20%" > </td> 
</tr>  

 
</table>

<br>	

<div  style="text-align:center;font-weight:bolder; font-size:0.7em;"><u>MOYEN DE MESURE</u></div>
<br>

<span style="font-size:0.8em;">Masse étalon CE: <span>

<br><br>

  <legend style="font-size: 1em; font-weight: bold; color: red;">Fidélité charge à controler à max/2</legend><br>
            <table border="1"  style="text-align:center; ">
              <tr >
    <th>Points essais</th>  <th>Valeurs étalons</th>  <th>Valeur lue</th>  <th>Ecart maximal</th> <th>Tolérence</th>
              </tr>
<tr>
    <td>jdjj</td>
     <td></td>
     <td></td>
     <td rowspan="4">23</td>

      <td rowspan="4" colspan="4"> </td>
</tr>

<tr>
    <td></td>
     <td></td>
     <td></td>
</tr>
<tr>
    <td></td>
     <td></td>
     <td></td>
     
</tr>
<tr>
    <td></td>
     <td></td>
     <td></td>
     
</tr>

 <tr>
    <th> Fidelité correcte ?</th>
     <td colspan="4" class="text-cente">
            
      </td>
       
   </tr>
              </table>


<br><br>

 <legend style="font-size: 1em; font-weight: bold; color: red;">Essai de justesse</legend><br>
            <table border="1" class="tabl" style="text-align:center;" cellspan="3">
              <tr >
    <th>Poids essai</th>  
    <th>Valeurs nomminal</th>  
    <th>Valeur lu en montée</th>
     <th>Valeur lu en descente</th> 
      <th>Moyenne de justesse</th> 
     <th>Indication + charge de sensibilité</th> 
     <th>Incertitude</th>
              </tr>
<tr>
    <td>
      </td>
     <td></td>
     <td></td>
      <td></td>
       <td></td>
       <td></td>
      <td></td>
     
</tr>

<tr><td>
    </td>
     <td></td>
     <td></td>
      <td></td>
       <td></td>
       <td></td>
      <td></td>
     
</tr>
<tr><td>
     </td>
     <td></td>
     <td></td>
      <td></td>
       <td></td>
       <td></td>
      <td></td>
     
</tr>
<tr> <td>
     </td>
     <td></td>
     <td></td>
      <td></td>
       <td></td>
       <td></td>
      <td></td>
     
</tr>

 <tr>

    <th>Justesse correcte ?</th>
     <td colspan="6" class="text-cente">
           
      </td>
       
   </tr>
    </table>




<br>
   <br> <legend style="font-size: 1em; font-weight: bold; color: red;">Excentration: charge à controler à max/3</legend><br>
            <table border="1" class="tabl" style="text-align:center;">
              <tr >
    <th>Position</th>  
    <th>1</th>  
    <th>2</th>
     <th>3</th> 
      <th>4</th> 
     <th>5</th> 
     <th>Tolérence</th>
              </tr>
   <tr>
     <th>Indication relevée</th>
    <td></td>
     <td></td>
     <td></td>
      <td></td>
       <td></td>
       <td></td>
    </tr>
    <tr>
    <th>Excentration correcte ?</th>
     <td colspan="6" class="text-cente">  
      </td>
      </tr>
          </table>


<br>


  
';  
 
$obj_pdf->writeHTML($content);  
$obj_pdf->Output('file.pdf', 'I');  

?>