 <!-- az-header -->
  <div class="skiplinks container-fluid">
  <a href="#mainNav" class="sr-only sr-only-focusable">Skip to main navigation</a>
  <a href="#content" class="sr-only sr-only-focusable">Skip to content</a>
  </div>

 <nav role="navigation" class="o-stepbar" aria-label="Checkout process">
    <p class="float-left mt-2 mr-2 font-weight-bold d-sm-none">Step</p>
    <ol>
      <li class="stepbar-item ">
        <a class="stepbar-link" href="<?php echo $this->baseUrl();?>/certificat/balance/" title="retour à la page precedante" >Retour</a>
      </li>
      <li class="stepbar-item ">
        <a class="stepbar-link" href="<?php echo $this->baseUrl();?>/certificat/temperature/" title="2. certificat d'étalonnage du four"   >Four </a>
      </li>
      <li class="stepbar-item current">
        <a class="stepbar-link" href="<?php echo $this->baseUrl();?>/certificat/thermometre/" aria-current="step" title="3. Certificat d'étalonnage du thermometre"> thermometre</a>
      </li>
      <li class="stepbar-item">
        <a class="stepbar-link" href="<?php echo $this->baseUrl();?>/certificat/etulive/" title="4. Certificat d'étalonnage de l'Etulive">Etulive</a>
      </li>
      <li class="stepbar-item" >
        <a class="stepbar-link" href="<?php echo $this->baseUrl();?>/certificat/baindemarin/" title="4. Certificat d'étalonnage de marin">Bain de marin</a>
      </li>

       
    </ol>
  </nav>

  <main role="main" id="content" class=" my-2">
   
      <form role="form" id="myForm"  method="post" action="<?php echo $this->baseUrl(); ?>/certificat/eprouvette/certificateprouvette">
         <div class="row">
        <div class="col-sm-4">
          
            <fieldset  style="background-color:#6495ED; border: 1px solid black;">
                        <legend style="font-size: 1em; font-weight: bold;" class="text-center">Remplissage des champs</legend>
            <div class="row">
              <div class="col-lg-6">
             <div class="form-group ">
              <label for="delivrance" class="is-required">Delivré à</label>
              <input type="text" class="form-contr" name="delivrance" id="delivrance" required/>
              </div>
              </div>
              <div class="col-lg-6">
             <div class="form-group ">
              <label for="titre" class="is-required">Titre:</label>
              <input type="text" class="form-contr" name="delivrance" id="titre" required/>
              </div>
              </div>
            
             <div class="col-lg-6">

            <div class="form-group ">
              <label for="designation" class="is-required">Designation:</label>
              <input type="text" class="form-contr" name="designation" id="designation" placeholder="" required>
            </div>

            <div class="form-group ">
              <label for="Constructeur" class="is-required">Constructeur:</label>
              <input type="text" class="form-cont" id="Constructeur" name="Constructeur" placeholder="" required>
            </div>
              
             <div class="form-group">
              <label for="date_emission" class="is-required">Type:</label>
              <input type="text" class="form-" name="type" id="type"  required aria-describedby="">
              <span class="form-text small text-muted" id="message_type"></span>
             </div>

             <div class="form-group">
              <label for="date_emission" class="is-required">Date d'émission:</label>
              <input type="date" class="form-" name="date_emission" id="date_emission"  required aria-describedby="">
              <span class="form-text small text-muted" id="helpTextPassword"></span>
             </div>

            
            <div class="form-group">
             <label for="numero_serie" class="is-required">N° Serie:</label>
             <input type="text" name="numero_serie" id="numero_serie">
            </div>

            </div>

            <div class="col-lg-6">

            <div class="form-group">
              <label for="plage_de_mesure">Plage de mesure:</label>
              <input type="text"  class="form-contr" name="plage_de_mesure"  id="plage_de_mesure"></input>
              <span class=" small erreur_portee" id=""></span>
            </div>

            <div class="form-group" >
              <label class="num_metroleb" for="">N°METROLEB:</label>
              <input type="text" class="" name="num_metroleb" id="num_metroleb"/>
              <span class=" small erreur_num_metroleb" id=""></span>
            </div>

             <div class="form-group" >
              <label class="label-echelon" for="">Echelon:</label>
              <input type="text" class="echelon" name="echelon" id="echelon"/>
              <span class=" small erreur_echelon" id="erreur_echelon"></span>
            </div>
               

            <div class="form-group" >
              <label class="localisation" for="">Localisation:</label>
              <input type="text" class="" name="localisation" id="localisation"/>
              <span class=" small erreur_nb_pesees" id=""></span>
            </div>
               
        <div class="form-group ">
           <label class="trace_choc" for=""> Lieu:</label>
   
            <label class="btn btn-secondary active">
              <input type="radio" name="en_laboratoire" id="en_laboratoire" value="en_laboratoire" autocomplete="off" checked>Labo
            </label>

            <label class="btn btn-secondary">
              <input type="radio" name="sur_site" value="sur_site" id="sur_site" autocomplete="off">site
            </label>
          </div>
          

            </div>

             <div class="form-group col-lg-12">
               <label class="methodedemesure" for="">Methode de mesure:</label>
              <textarea class="col-lg-12 " rows="5" cols="6"> </textarea>
           </div>
            </div>

           
            </fieldset>

    
            </div>
            
          

      <div class="col-lg-8">
          
    <fieldset  style="background-color:#6495ED; border: 1px solid black;">
                        <legend style="font-size: 1em; font-weight: bold; color:black;" class="text-center text-danger">Saisissez les valeurs de calcul pour le certificat d'etalonnage</legend>
             <div class="row"> 
             <div class="col-sm-4">  
                  <div class="form-group ">
              <input type="text" class="form-contr" name="masse" id="masse" placeholder="masse" required>
               </div>
              </div>
              <div class="col-sm-4">  
                  <div class="form-group ">
              <input type="text" class="form-contr" name="a" id="a" placeholder="a"required>
               </div>
              </div>
              <div class="col-sm-4">  
                  <div class="form-group ">
              <input type="text" class="form-contr" name="b" id="b" required placeholder="b">
               </div>
              </div>
              </div>
           

              <div class="table-responsive">
                
                <br> <legend style="font-size: 1em; font-weight: bold;  ">
                  <div class="form-group" >
              <label class="label-echelon" for="">Temperature:</label>
              <input type="text" class="temperature" name="temperature" id="temperature"/> °C+_°C
              <span class=" small erreur_temperature" id="erreur_temperature"></span>
            </div>
          </legend>

            <table border="1" class="tabl" style="  text-align: center; ">
              <tr>
              <th>Mesure:</th>  
              <th >VALEURS LUE SUR LE THERMOMETRE SOUS TEST (°c)</th>  
              <th >VALEURS DU THERMOMETRE ETALON (°C)</th>
                <th >ECARTS</th> 
                  <th >INCERTITUDE</th> 
              </tr>

             
  <tr>
     <td> 
    <input type="text" class="form-contr" name="a1" id="a1" placeholder="a1" required></td>
    <td> <input type="text" class="form-contr" name="b1" id="b1" placeholder="b1" required></td>
     <td><input type="text" class="form-contr" name="c1" id="c1" placeholder="c2" required></td>
     <td><input type="text" class="form-contr" name="d1" id="d1" placeholder="d1" required></td>
      <td><input type="text" class="form-contr" name="e1" id="e1" placeholder="e1" required></td>
    
  </tr>

<tr>
  <td> <input type="text" class="form-contr" name="a2" id="a2" placeholder="a2" required></td>
    <td>
      <input type="text" class="form-contr" name="b2" id="b2" placeholder="b2" required></td>
     <td><input type="text" class="form-contr" name="c2" id="c2" placeholder="c2" required></td>
     <td><input type="text" class="form-contr" name="d2" id="d2" placeholder="d2" required></td>
      <td><input type="text" class="form-contr" name="e2" id="e2" placeholder="e2" required></td>
    
</tr>

<tr>
  <td> <input type="text" class="form-contr" name="a3" id="a3" placeholder="a3" required></td>
    <td>
      <input type="text" class="form-contr" name="b3" id="b3" placeholder="b3" required></td>
     <td><input type="text" class="form-contr" name="c3" id="c3" placeholder="c3" required></td>
     <td><input type="text" class="form-contr" name="d3" id="d3" placeholder="d3" required></td>
      <td><input type="text" class="form-contr" name="e3" id="e3" placeholder="e3" required></td>
    
</tr>

<tr>
  <td> <input type="text" class="form-contr" name="a4" id="pa4" placeholder="a4" required></td>
    <td>
      <input type="text" class="form-contr" name="b4" id="b4" placeholder="b4" required></td>
     <td><input type="text" class="form-contr" name="c4" id="c4" placeholder="c4" required></td>
     <td><input type="text" class="form-contr" name="d4" id="d4" placeholder="d4" required></td>
      <td><input type="text" class="form-contr" name="e4" id="e4" placeholder="e4" required></td>
     
</tr>

 <tr>

    <th>Date du prohain etalonnage: ?</th>
     <td colspan="6" class="text-cente">
          <div class="btn-group col-lg-12" >
           <input type="date" name="date_etalonnage" id="date_etalonnage" > 
          </div>
    </td>
       
</tr>

  </table>
  
  </div>
  
   <br> <br> <br>
    <div class="col-lg-12" style="margin-top: 50px;">
        <div class="form-group ">
              <button type="submit" class="btn btn-danger">Télécharger Certificat d'etalonnage du four</button>
            </div>
      </div> 
  

</div>
    
</fieldset>
              
 </div>
    
</div>
  
</div>
  
</form>
 </main><!--/.container-->

  

      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
   <script src="<?php echo $this->baseUrl(); ?>/private/boosted/js/boosted.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.1/js/jquery.tablesorter.min.js" integrity="sha384-QnFIXbEfAgO7z63b/aNzTSdSNLoNiNX/mk/Ok+NpUNMnvriWLo5cOtB0OUCAdKNu" crossorigin="anonymous"></script>
   <script src="<?php echo $this->baseUrl(); ?>/private/boosted/material/material.min.js"></script>
    <script src="form.js"></script>

<script >
 
  $( "#masse" ).mouseout(function() {

        $('#p1').val($(this).val());
        $('#p2').val($(this).val()*2);
        $('#p3').val($(this).val()*3);
        $('#p4').val($(this).val()*4);

        $('#ps1').val($(this).val());
        $('#ps2').val($(this).val()*2);
        $('#ps3').val($(this).val()*3);
        $('#ps4').val($(this).val()*4);
   });



     function getEcartMaximal() {
       var moya=(parseInt($('#a1').val())+parseInt($('#a2').val())+parseInt($('#a3').val())+ parseInt($('#a4').val()))/4;

        var moyb=(parseInt($('#b1').val())+parseInt($('#b2').val())+parseInt($('#b3').val())+ parseInt($('#b4').val()) )/4;
        return moyb-moya;
     }

$( "#ecartmax" ).hover(function() {
        $(this).val(getEcartMaximal());
   });

$( "#mj1" ).hover(function() {
        $(this).val((parseInt($('#vm1').val())+parseInt($('#vd1').val()))/2);

         $("#ind1").val(parseInt($(this).val())+ parseInt($("#echellon").val()));
   });

$( "#mj2" ).hover(function() {
        $(this).val((parseInt($('#vm2').val())+parseInt($('#vd2').val()))/2);

         $("#ind2").val(parseFloat($(this).val())+ parseInt($("#echellon").val()));
   });

$( "#mj3" ).hover(function() {
        $(this).val((parseInt($('#vm3').val())+parseInt($('#vd3').val()))/2);

         $("#ind3").val(parseFloat($(this).val())+ parseInt($("#echellon").val()));
   });


$( "#mj4" ).hover(function() {
        $(this).val((parseInt($('#vm4').val())+parseInt($('#vd4').val()))/2);

         $("#ind4").val(parseFloat($(this).val())+ parseInt($("#echellon").val()));
   });

 $("#a,#b").mouseout(function(){
    $("#incert1").val(getIncertitude());
    $("#incert2").val(getIncertitude());
    $("#incert3").val(getIncertitude());
    $("#incert4").val(getIncertitude());
 });



function getIncertitude(){
var Ures=parseFloat($('#a').val())/(2*Math.sqrt(3));
var Uref=parseFloat($('#b').val())/Math.sqrt(3);
var Uc=Math.sqrt(Math.pow(Ures,2) + Math.pow(Uref,2));

var U=Math.sqrt(Math.pow(Uc,2))*2;

return U;
}
     function getNumber() {
        var minNumber = 9; // le minimum
        var maxNumber = 60; // le maximum

        var randomnumber = Math.floor(Math.random() * (maxNumber + 1) + minNumber); // la fonction magique
        return false;
    
    }   
    getNumber();
 
</script>