<div style="background-image: url('<?php echo $this->baseUrl();?>/public/images/recrutement-btp.jpg');">
<!-- az-header -->
  <div class="skiplinks container-fluid">
    <a href="#mainNav" class="sr-only sr-only-focusable">Skip to main navigation</a>
    <a href="#content" class="sr-only sr-only-focusable">Skip to content</a>
  </div>
<br>
 <nav role="navigation" class="o-stepbar" aria-label="Checkout process" >
    <p class="float-left mt-2 mr-2 font-weight-bold d-sm-none">Step</p>
    <ol style="background-color: #FFFFFF!important;">
      <li class="stepbar-item  ">
        <a class="stepbar-link" href="<?php echo $this->baseUrl();?>/certificat/balance/" title="certificat d'étalonnage de balance" >balance</a>
      </li>
      <li class="stepbar-item ">
        <a class="stepbar-link" href="#" title="2. certificat d'étalonnage d'éprouvette graduée" >éprouvette </a>
      </li>
      <li class="stepbar-item ">
        <a class="stepbar-link" href="#" title="3. Certificat d'étalonnage de la central à beton" > Centrale à beton</a>
      </li>
      <li class="stepbar-item">
        <a class="stepbar-link" href="#" title="4. Certificat d'étalonnage de comparateur">Comparateur</a>
      </li>
      <li class="stepbar-item">
        <a class="stepbar-link" href="#" title="5. Certificat d'étalonnage de l'arranchement de carreaux">Arrachemant de carreaux</a>
      </li>
      <li class="stepbar-item">
        <a class="stepbar-link" href="#" title="6. Certificat d'étalonnage de l'arranchement ">Equi. de pression</a>
      </li>
       <li class="stepbar-item">
        <a class="stepbar-link" href="#" title="7. Certificat d'étalonnage de l'arranchement de carreaux">Arrachement de carreaux</a>
      </li>

       
    </ol>
  </nav>


<div style="height: 530px;">
    
</div>

</div>

   <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
   <script src="<?php echo $this->baseUrl(); ?>/private/boosted/js/boosted.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.1/js/jquery.tablesorter.min.js" integrity="sha384-QnFIXbEfAgO7z63b/aNzTSdSNLoNiNX/mk/Ok+NpUNMnvriWLo5cOtB0OUCAdKNu" crossorigin="anonymous"></script>
   <script src="<?php echo $this->baseUrl(); ?>/private/boosted/material/material.min.js"></script>
    <script src="form.js"></script>