<!DOCTYPE html>
<html>
<head>
 <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Metroleb</title>
    <link rel="preload" href="<?php echo $this->baseUrl(); ?>/private/boosted/fonts/HelvNeue55_W1G.woff2"
          as="font" type="font/woff2" crossorigin="anonymous">
    <link rel="preload" href="<?php echo $this->baseUrl(); ?>/private/boosted/fonts/HelvNeue75_W1G.woff2"
          as="font" type="font/woff2" crossorigin="anonymous">
    <link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/orangeHelvetica.min.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/orangeIcons.min.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/boosted.min.css" rel="stylesheet"/>
    <link href="example.css" rel="stylesheet">
    <link rel="preconnect" href="https://code.jquery.com" crossorigin="anonymous">
    <link rel="preconnect" href="https://cdnjs.cloudflare.com" crossorigin="anonymous">
    <link href="<?php echo $this->baseUrl(); ?>/private/boosted/datatables/plugins/bootstrap/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
  <link href="<?php echo $this->baseUrl(); ?>/private/boosted/datatables/export/buttons.dataTables.min.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/private/font-awesome/css/font-awesome.min.css">


 <style type="text/css">
             main #localContainer{margin-top: -5%!important;}
            .badge{border-radius: 50px 50px 50px 50px!important;}

           .validerBtn{background-color: #00FF00!important; color:black; font-weight: bolder;  }
            .rejeterBtn{background-color: red!important; color:black; font-weight: bolder;}
             .validerBtn,.rejeterBtn{ display: inline-block; border-radius:50px 50px 50px 50px;}
            .rejeterBtn:hover,.validerBtn:hover{color: #FFFFFF; background-color: black!important;}
 </style>
</head>
  <!-- header -->
        <header role="banner">
      <nav role="navigation" class="navbar navbar-dark bg-dark navbar-expand-md" aria-label="Main navigation">
        <div class="container-fluid">
          <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/">
            <img src="<?php echo $this->baseUrl(); ?>/public/images/logo-metrolab.png" alt="Back to homepage" title="Back to homepage" width="50" height="50"/>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#orange-navbar-collapse" aria-controls="orange-navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse justify-content-between collapse" id="orange-navbar-collapse">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link d-inline-flex align-items-center" href="<?php echo $this->baseUrl(); ?>/index">
                  Accueil
                  <span class="icon icon-home ml-1" aria-hidden="true"></span>
                </a>
              </li>
              <li class="nav-item">
               <?php if($this->page=="add"): ?>
                <a class="nav-link d-inline-flex align-items-center" href="<?php echo $this->baseUrl(); ?>/snag/pda/import">
                  Téléchargement
                  <span class="svg-setting ml-1" aria-hidden="true"></span>
                </a>
              <?php endif; ?>

              <?php if($this->page=="import"): ?>
                <a class="nav-link d-inline-flex align-items-center" href="<?php echo $this->baseUrl(); ?>/snag/pda/add">
                  Enregistrement
                  <span class="svg-setting ml-1" aria-hidden="true"></span>
                </a>
              <?php endif; ?>
              </li>

              <li class="nav-item">
                <a class="nav-link d-inline-flex align-items-center" href="<?php echo $this->baseUrl(); ?>/snag/sendbox/setting">
                  gesition de calcul
                  <span class="fa fa-setting ml-1" aria-hidden="true"></span>
                </a>
              </li>

             
            </ul>
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <button type="button" class="nav-link btn btn-link btn-inverse dropdown-toggle d-flex align-items-center" data-toggle="dropdown">
                  <span class="svg-avatar mr-1" aria-hidden="true"></span>
                  <span>Bonjour <span class="text-primary">Utilisateur</span></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li><a class="dropdown-item" href="#">Logout</a></li>
                 
                </ul>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
      </nav>
    </header>
    <!-- az-header -->

  <body class="az-body">
     <main role="main" id="content" class=" my-5">
  <?php echo $this->layout()->content; ?>
 </main>
  
  </body>


</html>
