
<!DOCTYPE html>
<html lang="fr" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Metroleb</title>
    <link rel="preload" href="<?php echo $this->baseUrl(); ?>/private/boosted/fonts/HelvNeue55_W1G.woff2"
          as="font" type="font/woff2" crossorigin="anonymous">
    <link rel="preload" href="<?php echo $this->baseUrl(); ?>/private/boosted/fonts/HelvNeue75_W1G.woff2"
          as="font" type="font/woff2" crossorigin="anonymous">
    <link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/orangeHelvetica.min.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/orangeIcons.min.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/boosted.min.css" rel="stylesheet"/>
    <link href="example.css" rel="stylesheet">
    <link rel="preconnect" href="https://code.jquery.com" crossorigin="anonymous">
    <link rel="preconnect" href="https://cdnjs.cloudflare.com" crossorigin="anonymous">
    <link href="<?php echo $this->baseUrl(); ?>/private/boosted/datatables/plugins/bootstrap/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
  <link href="<?php echo $this->baseUrl(); ?>/private/boosted/datatables/export/buttons.dataTables.min.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/private/font-awesome/css/font-awesome.min.css">

 <style type="text/css">
   ul li{ list-style-type: none!important; }

     body{font-family: helvertica;}
   
 </style>

  </head>

<body>

    <!-- header -->
       <header role="banner">
    <nav role="navigation" id="mainNav" class="navbar navbar-dark bg-dark navbar-expand-md" aria-label="Main navigation">
      <div class="container-fluid">
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/">
          <img src="<?php echo $this->baseUrl(); ?>/public/images/logo-metrolab.png"   class="d-inline-block align-bottom mr-3" alt="Back to homepage" title="Back to homepage" width="50" height="50" loading="lazy"/>
          <span class="h1 mb-0">METROLEB</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#orange-navbar-collapse" aria-controls="orange-navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse justify-content-between collapse" id="orange-navbar-collapse">
          <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="<?php echo $this->baseUrl(); ?>/certificat">Accueil</a></li>
            <li class="nav-item"><a class="nav-link" href="<?php echo $this->baseUrl(); ?>/certificat2">Autre Certificat</a></li>
          </ul>
          <ul class="navbar-nav">
             <li class="nav-item dropdown">
              <button type="button" class="nav-link btn btn-link btn-inverse dropdown-toggle d-flex align-items-center" data-toggle="dropdown">
                <span class="svg-avatar mr-1" aria-hidden="true"></span>
                <span> <span class="text-primary">Admin</span></span>
              </button>
              <ul class="dropdown-menu dropdown-menu-right">
                <li><a class="dropdown-item" href="#">Deconnexion</a></li>
                <li><a class="dropdown-item" href="#">Paramettre</a></li>
              </ul>
            </li>

            <li class="nav-item dropdown">
              <button type="button" class="nav-link btn btn-link btn-inverse dropdown-toggle d-flex align-items-center" data-toggle="dropdown">
               <!-- <span class="icon-international-globe h4 mb-0 mr-1" aria-hidden="true"></span> -->
                <span></span>
              </button>
              <ul class="dropdown-menu dropdown-menu-right">
                <li><a class="dropdown-item" href="#" lang="fr" hreflang="fr">Français</a></li>
                <li><a class="dropdown-item" href="#" aria-current="page">Anglais</a></li>
              </ul>
            </li>
           
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    
  </header>

   
      <?php echo $this->layout()->content;?>
   

    <footer role="contentinfo" class="o-footer mt-auto">
      <div class="o-footer-bottom">
        <div class="container-fluid">
          <p class="my-2">© Metro-Lab 2020</p>
        </div>
      </div>
    </footer>

   
    
  </body>


</html>

