<!DOCTYPE html>
<html lang="en" class="h-100"  xmlns:th="http://www.thymeleaf.org">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bienvenue</title>
    <link rel="preload" href="<?php echo $this->baseUrl(); ?>/private/boosted/fonts/HelvNeue55_W1G.woff2"
          as="font" type="font/woff2" crossorigin="anonymous">
    <link rel="preload" href="<?php echo $this->baseUrl(); ?>/private/boosted/fonts/HelvNeue75_W1G.woff2"
          as="font" type="font/woff2" crossorigin="anonymous">
    <link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/orangeHelvetica.min.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/orangeIcons.min.css" rel="stylesheet">
    
    <link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/boosted.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="example.css" rel="stylesheet">
    <link rel="preconnect" href="https://code.jquery.com" crossorigin="anonymous">
    <link rel="preconnect" href="https://cdnjs.cloudflare.com" crossorigin="anonymous">
    
   <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/private/font-awesome/css/font-awesome.min.css">
              
  </head>
  <body class="d-flex flex-column h-100">
    <div class="skiplinks container-fluid">
      <a href="#content" class="sr-only sr-only-focusable">Skip to edit form</a>
    </div>
    <header role="banner">
      <nav role="navigation" class="navbar navbar-dark bg-dark navbar-expand-md" aria-label="Main navigation">
        <div class="container-fluid">
          <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/">
            <img src="<?php echo $this->baseUrl(); ?>/public/images/logo-metrolab.png"  alt="Back to homepage" title="Back to homepage" width="100" height="100"/>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#orange-navbar-collapse" aria-controls="orange-navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="navbar-collapse justify-content-between collapse" id="orange-navbar-collapse">
          <ul class="navbar-nav">
           
            
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <button type="button" class="nav-link btn btn-link btn-inverse dropdown-toggle d-flex align-items-center" data-toggle="dropdown">
                
                <span>Bonjour <span class="svg-avatar mr-1" aria-hidden="true"></span><span class="text-primary" >Admin</span></span>
              </button>
              <ul class="dropdown-menu dropdown-menu-right">
                <li><a class="dropdown-item" href="auth/logout">Logout</a></li>
                
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>
  </header>

    <main role="main" id="content" class="container-fluid my-5">

               <?php echo $this->layout()->content; ?>

    </main><!--/.container-->

    <footer role="contentinfo" class="o-footer mt-auto">
      <div class="o-footer-bottom">
        <div class="container-fluid">
           <p class="my-2">© Metro-Lab 2020</p>
        </div>
      </div>
    </footer>

  </body>
  </html>