<!DOCTYPE html>
<html lang="en"  xmlns:th="http://www.thymeleaf.org">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Orange and Boosted contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Authentification offre salariée</title>

    <link rel="canonical" href="https://boosted.orange.com/docs/4.4/examples/sign-in/">

    <!-- Boosted mod -->
    <link rel="preload" href="<?php echo $this->baseUrl(); ?>/private/boosted/fonts/HelvNeue55_W1G.woff2"
          as="font" type="font/woff2" crossorigin="anonymous">
    <link rel="preload" href="<?php echo $this->baseUrl(); ?>/private/boosted/fonts/HelvNeue75_W1G.woff2"
          as="font" type="font/woff2" crossorigin="anonymous">
    <link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin="anonymous">
    <link rel="preconnect" href="https://code.jquery.com" crossorigin="anonymous">
    <link rel="preconnect" href="https://cdnjs.cloudflare.com" crossorigin="anonymous">
    <!-- end mod -->
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/private/font-awesome/css/font-awesome.min.css">
    <!-- tarteaucitron -->
<link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/tarteaucitronboosted.css" rel="stylesheet">
<!-- Swiper -->
<link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/vendor/swiper.min.css" rel="stylesheet">
<!-- Boosted core CSS -->
  <!-- Helvetica -->
  <link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/orangeHelvetica.min.css" rel="stylesheet">
  <!-- orangeIcons -->
  <link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/orangeIcons.min.css" rel="stylesheet">
  <link href="<?php echo $this->baseUrl(); ?>/private/boosted/css/boosted.min.css" rel="stylesheet">
<!-- end mod -->
    <!-- Favicons -->
<link rel="apple-touch-icon" href="<?php echo $this->baseUrl(); ?>/private/boosted/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="<?php echo $this->baseUrl(); ?>/private/boosted/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="<?php echo $this->baseUrl(); ?>/private/boosted/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="<?php echo $this->baseUrl(); ?>/private/boosted/img/favicons/manifest.json">
<link rel="mask-icon" href="<?php echo $this->baseUrl(); ?>/private/boosted/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="<?php echo $this->baseUrl(); ?>/private/boosted/img/favicons/favicon.ico">
<meta name="msapplication-config" content="<?php echo $this->baseUrl(); ?>/private/boosted/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#000000">
</head>


  <body class="text-center">

    <!-- header -->
    <?php echo $this->layout()->content; ?>

  
  </body>


</html>
